// Centralized URL constants mirroring the backend blueprints
export const API = {
  AUTH: {
    REGISTER: "/auth/register",
    LOGIN: "/auth/login",
    ME: "/auth/me",
    LOGOUT: "/auth/logout",
    DEPARTMENTS: "/auth/departments",
    DESIGNATIONS: "/auth/designations",
  },
  USERS: {
    LIST: "/users/",
    CREATE: "/users/",
    COUNT: "/users/count",
    LOGIN: "/users/login",
    GET: (id) => `/users/${id}`,
    UPDATE: (id) => `/users/${id}`,
    DELETE: (id) => `/users/${id}`,
    PROFILE_GET: (id) => `/users/profile/${id}`,
    PROFILE_UPDATE: (id) => `/users/profile/${id}`,
  },
  EMPLOYEES: {
    LIST: "/employees/",
    CREATE: "/employees/",
    GET: (id) => `/employees/${id}`,
    UPDATE: (id) => `/employees/${id}`,
    DELETE: (id) => `/employees/${id}`,
    SALARY_LIST: "/employees/salary",
    SALARY_GET: (id) => `/employees/${id}/salary`,
    SALARY_UPDATE: (id) => `/employees/${id}/salary`,
    SALARY_RESET: (id) => `/employees/${id}/salary`,
    PAYSLIP: (id) => `/employees/${id}/payslip`,
    CHECKIN: "/employees/checkin",
    CHECKOUT: "/employees/checkout",
    MANUAL_ATTENDANCE: "/employees/manual-attendance",
    MANUAL_ATTENDANCE_ITEM: (id) => `/employees/manual-attendance/${id}`,
    ATTENDANCE: (id) => `/employees/${id}/attendance`,
  },
  MASTER: {
    DEPARTMENTS: "/departments",
    DEPARTMENT_GET: (id) => `/departments/${id}`,
    DEPARTMENT_UPDATE: (id) => `/departments/${id}`,
    DEPARTMENT_DELETE: (id) => `/departments/${id}`,
    DESIGNATIONS: "/designations",
    DESIGNATION_GET: (id) => `/designations/${id}`,
    DESIGNATION_UPDATE: (id) => `/designations/${id}`,
    DESIGNATION_DELETE: (id) => `/designations/${id}`,
    LEAVE_TYPES: "/leave-types",
    LEAVE_TYPE_GET: (id) => `/leave-types/${id}`,
    LEAVE_TYPE_UPDATE: (id) => `/leave-types/${id}`,
    LEAVE_TYPE_DELETE: (id) => `/leave-types/${id}`,
  },
  ATTENDANCE: {
    LIST: "/attendance/",
    REPORT: "/attendance/report",
    SALARY_REPORT: "/attendance/salary-report",
  },
  NETWORK: {
    LIST: "/network/",
  },
  LEAVES: {
    LIST: "/leaves/",
    CREATE: "/leaves/",
    GET: (id) => `/leaves/${id}`,
    UPDATE: (id) => `/leaves/${id}`,
    DELETE: (id) => `/leaves/${id}`,
    APPROVE: (id) => `/leaves/${id}/approve`,
    REJECT: (id) => `/leaves/${id}/reject`,
  },
  ROLES: {
    LIST: "/roles/",
    CREATE: "/roles/",
    GET: (id) => `/roles/${id}`,
    UPDATE: (id) => `/roles/${id}`,
    DELETE: (id) => `/roles/${id}`,
  },
  DASHBOARD: {
    STATS: "/dashboard/stats",
  },
};
