// Centralized URL constants mirroring the backend blueprints
export const API = {
  AUTH: {
    REGISTER: "/auth/register",
    LOGIN: "/auth/login",
    ME: "/auth/me",
    LOGOUT: "/auth/logout",
    DEPARTMENTS: "/auth/departments",
    DESIGNATIONS: "/auth/designations",
    FORGOT_PASSWORD: "/auth/forgot-password",
    VERIFY_OTP: "/auth/verify-otp",
    RESET_PASSWORD: "/auth/reset-password",
    CHANGE_PASSWORD: "/auth/change-password",
  },
  USERS: {
    LIST: "/users/",
    CREATE: "/users/",
    COUNT: "/users/count",
    LOGIN: "/users/login",
    GET: (id) => `/users/${id}`,
    UPDATE: (id) => `/users/${id}`,
    DELETE: (id) => `/users/${id}`,
    PROFILE_GET: (id) => `/users/profile/${id}`,
    PROFILE_UPDATE: (id) => `/users/profile/${id}`,
  },
  EMPLOYEES: {
    LIST: "/employees/",
    CREATE: "/employees/",
    GET: (id) => `/employees/${id}`,
    UPDATE: (id) => `/employees/${id}`,
    DELETE: (id) => `/employees/${id}`,
    SALARY_LIST: "/employees/salary",
    SALARY_GET: (id) => `/employees/${id}/salary`,
    SALARY_UPDATE: (id) => `/employees/${id}/salary`,
    SALARY_RESET: (id) => `/employees/${id}/salary`,
    PAYSLIP: (id) => `/employees/${id}/payslip`,
    CHECKIN: "/employees/checkin",
    CHECKOUT: "/employees/checkout",
    MANUAL_ATTENDANCE: "/employees/manual-attendance",
    MANUAL_ATTENDANCE_ITEM: (id) => `/employees/manual-attendance/${id}`,
    ATTENDANCE: (id) => `/employees/${id}/attendance`,
  },
  MASTER: {
    DEPARTMENTS: "/departments",
    DEPARTMENT_GET: (id) => `/departments/${id}`,
    DEPARTMENT_UPDATE: (id) => `/departments/${id}`,
    DEPARTMENT_DELETE: (id) => `/departments/${id}`,
    DESIGNATIONS: "/designations",
    DESIGNATION_GET: (id) => `/designations/${id}`,
    DESIGNATION_UPDATE: (id) => `/designations/${id}`,
    DESIGNATION_DELETE: (id) => `/designations/${id}`,
    LEAVE_TYPES: "/leave-types",
    LEAVE_TYPE_GET: (id) => `/leave-types/${id}`,
    LEAVE_TYPE_UPDATE: (id) => `/leave-types/${id}`,
    LEAVE_TYPE_DELETE: (id) => `/leave-types/${id}`,
    HOLIDAYS: "/organization/holiday",
    HOLIDAY_GET: (id) => `/organization/holiday/${id}`,
    HOLIDAY_UPDATE: (id) => `/organization/holiday/${id}`,
    HOLIDAY_DELETE: (id) => `/organization/holiday/${id}`,
    HOLIDAY_SYNC_GOVERNMENT: "/organization/holiday/sync-government",
    HOLIDAY_UNSYNC_GOVERNMENT:"/organization/holiday/unsync-government",
    HOLIDAY_PREVIEW_GOVERNMENT: "/organization/holiday/preview-government",
    HOLIDAY_SYNC_OFFICE_SUNDAYS:  "/organization/holiday/sync-office-sundays",
    HOLIDAY_SYNC_OFFICE_SUNDAYS_BY_YEAR: "/organization/holiday/sync-office-sundays",
    HOLIDAY_REPORT: "/organization/holiday/report", 
    COMPANIES: "/companies",
    COMPANY_GET: (id) => `/companies/${id}`,
    COMPANY_UPDATE: (id) => `/companies/${id}`,
    COMPANY_DELETE: (id) => `/companies/${id}`,
    BRANCHES: "/branches",
    BRANCH_GET: (id) => `/branches/${id}`,
    BRANCH_UPDATE: (id) => `/branches/${id}`,
    BRANCH_DELETE: (id) => `/branches/${id}`,
    COMPANY_BRANCHES: (companyId) => `/companies/${companyId}/branches`,
  },
  ATTENDANCE: {
    LIST: "/attendance/",
    MONTHLY_SUMMARY: "/attendance/monthly-summary",
    REPORT: "/attendance/report",
    SALARY_REPORT: "/attendance/salary-report",
    SETTINGS: "/attendance/settings",
  },
  NETWORK: {
    LIST: "/network/",
  },
  LEAVES: {
    LIST: "/leaves/",
    CREATE: "/leaves/",
    GET: (id) => `/leaves/${id}`,
    UPDATE: (id) => `/leaves/${id}`,
    DELETE: (id) => `/leaves/${id}`,
    APPROVE: (id) => `/leaves/${id}/approve`,
    REJECT: (id) => `/leaves/${id}/reject`,
  },
  ROLES: {
    LIST: "/roles/",
    CREATE: "/roles/",
    GET: (id) => `/roles/${id}`,
    UPDATE: (id) => `/roles/${id}`,
    DELETE: (id) => `/roles/${id}`,
    PERMISSIONS_CATALOG: "/roles/permissions/catalog",
    ROLE_PERMISSIONS: (id) => `/roles/${id}/permissions`,
  },
  DASHBOARD: {
    STATS: "/dashboard/stats",
  },
  EMPLOYEE_LIFECYCLE: {
    DOCUMENTS: "/employee-documents/",
    DOCUMENTS_ITEM: (id) => `/employee-documents/${id}`,
    PERMISSIONS: "/employee-permissions/",
    PERMISSIONS_ITEM: (id) => `/employee-permissions/${id}`,
    OVERTIME: "/overtime/",
    OVERTIME_ITEM: (id) => `/overtime/${id}`,
    PAYROLL: "/payroll/",
    PAYROLL_ITEM: (id) => `/payroll/${id}`,
    PAYROLL_REPORT: "/payroll/report",
    PERFORMANCE: "/performance/",
    PERFORMANCE_ITEM: (id) => `/performance/${id}`,
    TRAINING: "/training/",
    TRAINING_ITEM: (id) => `/training/${id}`,
    PROMOTIONS: "/promotions/",
    PROMOTIONS_ITEM: (id) => `/promotions/${id}`,
    TRANSFERS: "/transfers/",
    TRANSFERS_ITEM: (id) => `/transfers/${id}`, 
    RESIGNATIONS: "/resignations/",
    RESIGNATIONS_ITEM: (id) => `/resignations/${id}`,
    EXIT_MANAGEMENT: "/exit-management/",
    EXIT_MANAGEMENT_ITEM: (id) => `/exit-management/${id}`,
  },
  CRM: {
    LEADS: "/leads/",
    LEADS_ITEM: (id) => `/leads/${id}`,
    LEAD_CONVERT: (id) => `/leads/${id}/convert`,
    LEAD_UPLOADS: "/lead-uploads/",
    LEAD_UPLOADS_ITEM: (id) => `/lead-uploads/${id}`,
    LEAD_ASSIGN: (id) => `/leads/${id}/assign`,
    LEAD_STATUS_CHANGE: (id) => `/leads/${id}/status`,
    LEAD_ASSIGNMENT_HISTORY: (id) => `/leads/${id}/assignment-history`,
    LEAD_STATUS_HISTORY: (id) => `/leads/${id}/status-history`,
    INCENTIVE_SLABS: "/incentive-slabs/",
    INCENTIVE_SLABS_ITEM: (id) => `/incentive-slabs/${id}`,
    EMPLOYEE_INCENTIVES: "/employee-incentives/",
    EMPLOYEE_INCENTIVES_ITEM: (id) => `/employee-incentives/${id}`,
    EMPLOYEE_INCENTIVES_CALCULATE: "/employee-incentives/calculate",
    EMPLOYEE_TARGETS: "/employee-targets/",
    EMPLOYEE_TARGETS_ITEM: (id) => `/employee-targets/${id}`,
    LEAD_WEEKLY_SNAPSHOTS: "/lead-weekly-snapshots/",
    LEAD_WEEKLY_SNAPSHOTS_ITEM: (id) => `/lead-weekly-snapshots/${id}`,
    LEAD_WEEKLY_SNAPSHOTS_GENERATE: "/lead-weekly-snapshots/generate",
    CUSTOMERS: "/customers/",
    CUSTOMERS_ITEM: (id) => `/customers/${id}`,
    DEPARTMENT_HEADCOUNTS: "/department-headcounts/",
    DEPARTMENT_HEADCOUNTS_ITEM: (id) => `/department-headcounts/${id}`,
    FOLLOW_UPS: "/follow-ups/",
    FOLLOW_UPS_ITEM: (id) => `/follow-ups/${id}`,
    MEETINGS: "/meetings/",
    MEETINGS_ITEM: (id) => `/meetings/${id}`,
    QUOTATIONS: "/quotations/",
    QUOTATIONS_ITEM: (id) => `/quotations/${id}`,
    INVOICES: "/invoices/",
    INVOICES_ITEM: (id) => `/invoices/${id}`,
    INVOICES_REPORT: "/invoices/report",
    // NEW: per-invoice single-record download, distinct from the
    // aggregate INVOICES_REPORT above (date-range, multi-invoice).
    // Matches the new /invoices/<id>/download route in invoices.py.
    INVOICES_GENERATE_INCENTIVE: "/invoices/generate-incentive-invoice",
    INVOICES_DOWNLOAD: (id) => `/invoices/${id}/download`,
    PAYMENTS: "/payments/",
    PAYMENTS_ITEM: (id) => `/payments/${id}`,
    SUPPORT_TICKETS: "/support-tickets/",
    SUPPORT_TICKETS_ITEM: (id) => `/support-tickets/${id}`,
    SUPPORT_TICKETS_HISTORY: (id) => `/support-tickets/${id}/history`,
  },
  FINANCE: {
    ACCOUNTS: "/accounts/",
    ACCOUNTS_ITEM: (id) => `/accounts/${id}`,
    VENDORS: "/vendors/",
    VENDORS_ITEM: (id) => `/vendors/${id}`,
    EXPENSES: "/expenses/",
    EXPENSES_ITEM: (id) => `/expenses/${id}`,
    EXPENSES_REPORT: "/expenses/report",
    INCOME: "/income/",
    INCOME_ITEM: (id) => `/income/${id}`,
  },
  REPORTS: {
    ATTENDANCE: "/attendance/report",
    LEAVE: "/leaves/report",
    PAYROLL: "/payroll/report",
    EMPLOYEE: "/employees/report",
    CRM: "/invoices/report",
    FINANCE: "/expenses/report",
  },
};